### ISSUE TITLE
Lecture 4, slide 9:

### ISSUE THREAD

**Issue by adam-gaia** [tsung-wei-huang/ece5960#3]
Lecture 4, slide 9:
The last bullet point should say 'queue instead of 'stack'

**Comment by adam-gaia** [comment]
And again on slide 11

**Comment by adam-gaia** [comment]
I've never made a github issue before. I know the swapping of 'stack' and 'queue' is pretty simple, but I wanted to create an issue to see how github works. Thanks!

**Comment by tsung-wei-huang** [comment]
@adam-gaia Thanks! Fixed the typo already :)
